### ISSUE TITLE
specify @main to install package

### ISSUE THREAD

**Issue by cjandrew** [hjsimpso/fungarium#9]
One minor issue with installation -- need to specify @main to install package, i.e.,

> install_github("hjsimpso/fungarium@main")

**Comment by hjsimpso** [comment]
Thanks for letting me know.  `install_github("hjsimpso/fungarium")` has been working for me and automatically defaulting to the main branch; however, to be more robust I've changed this code in the installation instructions to `install_github("hjsimpso/fungarium@*release")`, which should install the latest release of the package.
